/**
 * Demo 页面配置
 * ─────────────────────────────────────────────────────────────
 * 每个对象对应一个页面的 TikTokHome demo。
 * 字段说明：
 *   slide      — 对应 App.jsx 中 SLIDES 的 id（0-based），如 6 = 页面7
 *   label      — 右侧导航点悬停时显示的名称
 *   video      — 视频文件路径（相对于 src/assets/figma/）
 *   avatar     — 头像文件路径（相对于 src/assets/figma/）
 *   username   — 用户名（含 @）
 *   description — 视频描述文字
 *   captionOffset — 用户名/弹幕按钮整体下移像素数（默认 0）
 *   danmakus   — 预设弹幕列表，格式：{ text: "弹幕内容", row: 0|1|2 }
 *                row 0 = 第一行，row 1 = 第二行，row 2 = 第三行
 * ─────────────────────────────────────────────────────────────
 */

const DEMOS = [
  {
    slide: 6,
    label: 'O1 | 弹幕跟发',
    leftPanel: true,
    video: 'usecase1.mov',
    avatar: 'usecase1.jpg',
    username: '@圆滚滚的瑞吉',
    description: '太多粉丝喜欢我们瑞吉了真棒～#瑞吉#奇妙的动物#动物的迷惑行为',
    captionOffset: 0,
    danmakus: [
      { text: '这死出', row: 0 },
      { text: '你看，又扭', row: 0 },
      { text: '水中小狗', row: 0 },
      { text: '你嗷什么', row: 0 },
      { text: '我不行了', row: 0 },
      { text: '哈哈哈好好笑', row: 0 },
      { text: '好萌啊你', row: 0 },
      { text: '舒服了', row: 0 },
      { text: '聪明宝宝', row: 0 },
      { text: '👽：收到', row: 1 },
      { text: '你叫啥', row: 1 },
      { text: '男神', row: 1 },
      { text: '邪恶QQ肠', row: 1 },
      { text: '神了吧', row: 1 },
      { text: '聪明宝宝', row: 1 },
      { text: '多吃多叫', row: 1 },
      { text: '好可爱啊', row: 1 },
      { text: '好多粉丝', row: 1 },
      { text: '收到', row: 1 },
      { text: '👽：收到', row: 1 },
      { text: '一顿连招', row: 1 },
      { text: '你看又扭', row: 1 },
      { text: '搔首弄姿', row: 1 },
      { text: '夯爆了', row: 2},
      { text: '每天都看', row: 2 },
      { text: '粉丝比我多', row: 2 },
      { text: '我去不早说', row: 2 },
      { text: '👽：收到', row: 2 },
      { text: '瑞吉说的对', row: 2 },
      { text: '笑死了吧', row: 2 },
      { text: '丝滑小曲', row: 2 },
      { text: '瑞吉说得好', row: 2 },
      { text: '知道了', row: 2 },
    ],
  },
  {
    slide: 7,
    label: 'O1 | 弹幕+1发送',
    video: 'usecase2.mov',
    avatar: 'usecase2.jpg',
    username: '@高冷兄弟',
    description: '你的男神已上线#刘耀文',
    captionOffset: 24,
    danmakus: [
      { text: '男神你随便吧', row: 0, plusOne: true, delay: 2000 },
      { text: '老公你随便吧', row: 0 },
      { text: '男神你随便吧', row: 0 },
      { text: '男神你随便吧', row: 0 },
      { text: '男神你随便吧', row: 0 },
      { text: '男神你随便吧', row: 0 },
      { text: '太帅了', row: 0 },
      { text: '神了吧', row: 0 },
      { text: '太帅了', row: 0 },
      { text: '男神你随便吧', row: 1 },
      { text: '男神你随便吧', row: 1 },
      { text: '男神你随便吧', row: 1 },
      { text: '太帅了', row: 1 },
      { text: '神了吧', row: 1 },
      { text: '太帅了', row: 1 },
      { text: '男神你随便吧', row: 1 },
      { text: '男神你随便吧', row: 1 },
      { text: '男神你随便吧', row: 1 },
      { text: '老公你随便吧', row: 1 },
      { text: '男神你随便吧', row: 1 },
      { text: '男神你随便吧', row: 1 },
      { text: '男神你随便吧', row: 1 },
      { text: '男神你随便吧', row: 1 },
      { text: '夯爆了', row: 2},
      { text: '男神！', row: 2 },
      { text: '男神你随便吧', row: 2 },
      { text: '男神你随便吧', row: 2 },
      { text: '男神你随便吧', row: 2 },
      { text: '男神你随便吧', row: 2 },
      { text: '男神你随便吧', row: 2 },
      { text: '男神你随便吧', row: 2 },
      { text: '老公你随便吧', row: 2 },
      { text: '男神你随便吧', row: 2 },
    ],
  },
  {
    slide: 8,
    label: 'O1 | 评论精选弹幕',
    video: 'usecase3.mov',
    avatar: 'usecase3.jpg',
    username: '@橘一橙 NiceFriend',
    description: '如何安稳度过二十几岁焦虑的”Odyssey时期”？很长的talking环节',
    captionOffset: 0,
    videoFit: 'contain-top',
    danmakus: [
      { text: '毕业找工作中', row: 0 },
      { text: '28岁三年没工作了', row: 0 },
      { text: '27岁研究生毕业没工作', row: 0 },
      { text: '我好像提前了', row: 0 },
      { text: '过了二十五岁找工作更难了', row: 0 },
      { text: '原来这叫做奥德赛', row: 0 },
      { text: '原来大家都有', row: 0 },
      { text: '阴暗潮湿的日子', row: 0 },
      { text: '这样啊', row: 0 },
      { text: '苦难', row: 1 },
      { text: '很痛苦很迷茫', row: 1 },
      { text: '焦虑源于方向感，焦虑源于自我认同', row: 1, featured: true, replies: 46 },
      { text: '大冒险时期', row: 1 },
      { text: '特别痛苦的时期', row: 1 },
      { text: '嘿嘿马里奥', row: 1 },
      { text: '28岁未成年', row: 1 },
      { text: '10后就不会了', row: 1 },
      { text: '我真的好讨厌这个阶段', row: 1 },
      { text: 'MyOdyssey', row: 1 },
      { text: '是的', row: 1 },
      { text: '虽然不能同时拥有一切', row: 1 },
      { text: '刚刚辞职回家', row: 1 },
      { text: '太对了', row: 1 },
      { text: '不管怎么选择都在失去另外一种人生', row: 2},
      { text: '很迷茫', row: 2 },
      { text: '我正处于这个阶段', row: 2 },
      { text: '晚期了', row: 2 },
      { text: '+1', row: 2 },
      { text: '毕业找工作中', row: 2 },
      { text: '困难时期', row: 2 },
      { text: '是啊我好焦虑', row: 2 },
      { text: '加速被社会驯化', row: 2 },
      { text: '真的诶', row: 2 },
    ],
  },

  {
    slide: 9,
    label: 'O2 | 评论精选弹幕',
    video: 'usecase4.mov',
    avatar: 'usecase4.png',
    username: '@尖端锐评玩家',
    description: '从夯到拉 锐评一下奶茶店#从夯到拉排名#内容过于真实#夯爆了',
    captionOffset: 0,
    videoScale: 0.8,
    videoOffsetY: -8,
    disclaimerMaskHeight: 200,
    danmakus: [
      { text: '夯', row: 0 },
      { text: '夯', row: 0 },
      { text: '拉完了', row: 0 },
      { text: '顶级', row: 0 },
      { text: '拉完了', row: 0 },
      { text: 'NPC', row: 0 },
      { text: '顶级', row: 0 },
      { text: '拉完了', row: 0 },
      { text: 'NPC', row: 0 },
      { text: '拉完了', row: 1 },
      { text: '拉完了', row: 1 },
      { text: '拉完了', row: 1 },
      { text: 'NPC', row: 1 },
      { text: '夯爆了', row: 1 },
      { text: '拉完了', row: 1 },
      { text: 'NPC', row: 1 },
      { text: '拉完了', row: 1 },
      { text: '拉完了', row: 1 },
      { text: '拉完了', row: 1 },
      { text: '拉完了', row: 1 },
      { text: '夯爆了', row: 1 },
      { text: 'NPC', row: 1 },
      { text: '夯拉了', row: 1 },
      { text: '拉完了', row: 2},
      { text: '顶级', row: 2 },
      { text: '拉完了', row: 2 },
      { text: '拉完了', row: 2 },
      { text: '夯', row: 2 },
      { text: 'NPC', row: 2 },
      { text: '人上人', row: 2 },
      { text: '拉完了', row: 2 },
      { text: '拉完了', row: 2 },
      { text: '顶级', row: 2 },
    ],
  },


  {
    slide: 10,
    label: 'O2 | xxx',
    emojiFloat: true,
    video: 'usecase5-1.mov',
    avatar: 'usecase5-1.jpg',
    username: '@小笼包（见过两次版）',
    description: '所有人Lets接接接#演唱会抢票',
    captionOffset: 24,
    videoScale: 0.7,
    videoOffsetY: -12,
    syncRows: true,
    danmakus: [
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 2},
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
    ],
  },

  {
    slide: 11,
    label: 'O2 | xxx',
    kiteDanmaku: true,
    disableCounter: true,
    willowLeaf: true,
    video: 'usecase6.mov',
    avatar: 'usecase6.jpg',
    username: '子扬ZYang',
    description: '又是清明雨上，不觉绿满江南 地点：杭州·茅家埠 2026.4.3',
    captionOffset: 0,
    danmakus: [
      { text: '清明雨上', row: 0 },
      { text: '清明时节雨纷纷', row: 0 },
      { text: '绿色生命力', row: 0 },
      { text: '清明安康', row: 0 },
      { text: '岁岁思故人', row: 0 },
      { text: '清明节安康', row: 0 },
      { text: '出门踏青', row: 0 },
      { text: '人间四月', row: 0 },
      { text: '清明雨上', row: 0 },
      { text: '想起了许嵩的歌', row: 1 },
      { text: '四月芳菲', row: 1 },
      { text: '又是一年清明时节', row: 1 },
      { text: '遥寄相思', row: 1 },
      { text: '愿故人无恙', row: 1 },
      { text: '有些伤感', row: 1 },
      { text: '打扫院子', row: 1 },
      { text: '黛草如烟', row: 1 },
      { text: '杨柳泛青', row: 1 },
      { text: '珍惜眼前人啊', row: 1 },
      { text: '珍惜当下', row: 1 },
      { text: '风景真好', row: 1 },
      { text: '空气很清新', row: 1 },
      { text: '又是清明', row: 1 },
      { text: '思念如连绵的雨', row: 2},
      { text: '春天来了', row: 2 },
      { text: '清明时节雨纷纷', row: 2 },
      { text: '清明下雨', row: 2 },
      { text: '小溪潺潺', row: 2 },
      { text: '思念堆积如山', row: 2 },
      { text: '万物生', row: 2 },
      { text: '好美', row: 2 },
      { text: '烟雨江南', row: 2 },
      { text: '杭州好美啊', row: 2 },
    ],
  },


  // ── 在此继续添加新的 demo ──────────────────────────────────
  // {
  //   slide: 8,          // 页面9
  //   label: '页面 9 · 用例 Demo',
  //   video: 'usecase3.mov',
  //   avatar: 'avatar-p9.jpg',
  //   username: '@用户名',
  //   description: '描述文字 #标签',
  //   captionOffset: 0,
  //   danmakus: [
  //     { text: '弹幕内容', row: 0 },
  //   ],
  // },
];

// 自动从 danmakus 按 row 分组，生成各页背景文案池
DEMOS.forEach(demo => {
  if (demo.danmakus && demo.danmakus.length > 0) {
    const pool = [[], [], []];
    demo.danmakus.forEach(d => pool[d.row ?? 0].push(d.text));
    // 去重，空行 fallback 用其他行
    demo.bgTexts = pool.map((arr, i) => {
      const unique = [...new Set(arr)];
      return unique.length > 0 ? unique : [...new Set(pool.flat())];
    });
  }
});

export default DEMOS;
