/**
 * Demo 页面配置
 * ─────────────────────────────────────────────────────────────
 * 每个对象对应一个页面的 TikTokHome demo。
 * 字段说明：
 *   slide      — 对应 App.jsx 中 SLIDES 的 id（0-based），如 6 = 页面7
 *   label      — 右侧导航点悬停时显示的名称
 *   video      — 视频文件路径（相对于 src/assets/figma/）
 *   avatar     — 头像文件路径（相对于 src/assets/figma/）
 *   username   — 用户名（含 @）
 *   description — 视频描述文字
 *   captionOffset — 用户名/弹幕按钮整体下移像素数（默认 0）
 *   danmakus   — 预设弹幕列表，格式：{ text: "弹幕内容", row: 0|1|2 }
 *                row 0 = 第一行，row 1 = 第二行，row 2 = 第三行
 * ─────────────────────────────────────────────────────────────
 */

const DEMOS = [
  {
    slide: 0,
    label: '弹幕玩法说明',
    bgColor: '#2a2a2a',
    centerLogo: true,
    disableCounter: true,
    avatar: 'usecase1.jpg',
    username: '@圆滚滚的瑞吉',
    description: '太多粉丝喜欢我们瑞吉了真棒～#瑞吉#奇妙的动物#动物的迷惑行为',
    info: {
      tag: '💡 请在右侧试玩',
      title: '弹幕玩法说明',
      description: '1. 点击某条弹幕，点赞或者跟发这条弹幕\n2. 点击发弹幕按钮，用键盘打出弹幕内容，点击发送',
    },
    annotations: [
      { text: '弹幕区域', side: 'right', yInPhone: 135 },
      { text: '发弹幕按钮', side: 'left', yInPhone: 647 },
    ],
    danmakus: [
      { text: '这是一个弹幕', row: 0 },
      { text: '这是一个弹幕', row: 0 },
      { text: '这是一个弹幕', row: 0 },
      { text: '这是一个弹幕', row: 0 },
      { text: '这是一个弹幕', row: 0 },
      { text: '这是一个弹幕', row: 0 },
      { text: '这是一个弹幕', row: 0 },
      { text: '这是一个弹幕', row: 0 },
      { text: '这是一个弹幕', row: 1 },
      { text: '这是一个弹幕', row: 1 },
      { text: '这是一个弹幕', row: 1 },
      { text: '这是一个弹幕', row: 1 },
      { text: '这是一个弹幕', row: 1 },
      { text: '这是一个弹幕', row: 1 },
      { text: '这是一个弹幕', row: 1 },
      { text: '这是一个弹幕', row: 1 },
      { text: '这是一个弹幕', row: 2 },
      { text: '这是一个弹幕', row: 2 },
      { text: '这是一个弹幕', row: 2 },
      { text: '这是一个弹幕', row: 2 },
      { text: '这是一个弹幕', row: 2 },
      { text: '这是一个弹幕', row: 2 },
      { text: '这是一个弹幕', row: 2 },
      { text: '这是一个弹幕', row: 2 },
    ],
  },
  {
    slide: 2,
    label: '功能1 | 跟发弹幕',
    info: {
      tag: '功能 1',
      title: '跟发弹幕，\n基于已有的优质表达快速二创',
      description: '点击弹幕，tooltip 中新增 “跟发” 功能，聚合复制粘贴效果。\n点击后，弹幕文本快速复制到弹幕面板输入框中。',
    },
    disableCounter: true,
    annotations: [
      { text: '点击弹幕，再点击跟发', side: 'right', yInPhone: 135, icon: 'followsend' },
      { text: '打开声音，沉浸观看', side: 'right', yInPhone: 726 },
    ],
    video: 'https://g7wxjm6ewnwsi0wp.public.blob.vercel-storage.com/videos/usecase1.mov',
    avatar: 'usecase1.jpg',
    username: '@圆滚滚的瑞吉',
    description: '太多粉丝喜欢我们瑞吉了真棒～#瑞吉#奇妙的动物#动物的迷惑行为',
    captionOffset: 0,
    danmakus: [
      { text: '这死出', row: 0 },
      { text: '你看，又扭', row: 0 },
      { text: '水中小狗', row: 0 },
      { text: '你嗷什么', row: 0 },
      { text: '我不行了', row: 0 },
      { text: '哈哈哈好好笑', row: 0 },
      { text: '好萌啊你', row: 0 },
      { text: '舒服了', row: 0 },
      { text: '聪明宝宝', row: 0 },
      { text: '👽：收到', row: 1 },
      { text: '你叫啥', row: 1 },
      { text: '男神', row: 1 },
      { text: '邪恶QQ肠', row: 1 },
      { text: '神了吧', row: 1 },
      { text: '聪明宝宝', row: 1 },
      { text: '多吃多叫', row: 1 },
      { text: '好可爱啊', row: 1 },
      { text: '好多粉丝', row: 1 },
      { text: '收到', row: 1 },
      { text: '👽：收到', row: 1 },
      { text: '一顿连招', row: 1 },
      { text: '你看又扭', row: 1 },
      { text: '搔首弄姿', row: 1 },
      { text: '夯爆了', row: 2},
      { text: '每天都看', row: 2 },
      { text: '粉丝比我多', row: 2 },
      { text: '我去不早说', row: 2 },
      { text: '👽：收到', row: 2 },
      { text: '瑞吉说的对', row: 2 },
      { text: '笑死了吧', row: 2 },
      { text: '丝滑小曲', row: 2 },
      { text: '瑞吉说得好', row: 2 },
      { text: '知道了', row: 2 },
    ],
  },
  {
    slide: 3,
    label: '功能2 | 弹幕+1发送',
    info: {
      tag: '功能 2',
      title: '高频弹幕+1，\n即时表达认同，营造在场感',
      description: '+1 弹幕的样式与发送后样式类似，视觉隐喻吸引点击。\n点击后，原地展现为已发送样式。',
    },
    annotations: [
      { text: '捕捉 +1 弹幕并点击', side: 'right', yInPhone: 135 },
    ],
    disableCounter: true,
    video: 'https://g7wxjm6ewnwsi0wp.public.blob.vercel-storage.com/videos/usecase2.mov',
    avatar: 'usecase2.jpg',
    username: '@高冷兄弟',
    description: '你的男神已上线#刘耀文',
    captionOffset: 24,
    danmakus: [
      // +1 弹幕每 8 秒出现一次
      { text: '男神你随便吧', row: 0, plusOne: true, delay: 2000 },
      { text: '男神你随便吧', row: 1, plusOne: true, delay: 10000 },
      { text: '男神你随便吧', row: 2, plusOne: true, delay: 18000 },
      { text: '男神你随便吧', row: 0, plusOne: true, delay: 26000 },
      { text: '男神你随便吧', row: 1, plusOne: true, delay: 32000 },
      { text: '男神你随便吧', row: 1, plusOne: true, delay: 40000 },
      { text: '男神你随便吧', row: 1, plusOne: true, delay: 48000 },
      { text: '男神你随便吧', row: 1, plusOne: true, delay: 56000 },
      { text: '男神你随便吧', row: 1, plusOne: true, delay: 64000 },
      { text: '男神你随便吧', row: 1, plusOne: true, delay: 72000 },
      // 背景弹幕
      { text: '男神你随便吧', row: 0 },
      { text: '男神你随便吧', row: 0 },
      { text: '男神你随便吧', row: 0 },
      { text: '男神你随便吧', row: 1 },
      { text: '男神你随便吧', row: 1 },
      { text: '太帅了吧', row: 1 },
      { text: '男神你随便吧', row: 1 },
      { text: '男神你随便吧', row: 2 },
      { text: '男神你随便吧', row: 2 },
      { text: '男神你随便吧', row: 2 },
      { text: '神图有了', row: 1 },
    ],
  },
  {
    slide: 4,
    label: '功能3 | 评论精选弹幕',
    info: {
      tag: '功能 3',
      title: '评论精选弹幕，\n还原最熟悉的互动方式',
      description: '精选弹幕外露回复按钮，可跳转至弹幕面板查看。\n弹幕回复后，回复内容同步发送至弹幕区，达成渗透。',
    },
    disableCounter: true,
    annotations: [
      { text: '查看精选弹幕回复', side: 'right', yInPhone: 135 },
    ],
    video: 'https://g7wxjm6ewnwsi0wp.public.blob.vercel-storage.com/videos/usecase3.mov',
    avatar: 'usecase3.jpg',
    username: '@橘一橙 NiceFriend',
    description: '如何安稳度过二十几岁焦虑的”Odyssey时期”？很长的talking环节',
    captionOffset: 0,
    videoFit: 'contain-top',
    danmakus: [
      { text: '毕业找工作中', row: 0 },
      { text: '28岁三年没工作了', row: 0 },
      { text: '27岁研究生毕业没工作', row: 0 },
      { text: '我好像提前了', row: 0 },
      { text: '过了二十五岁找工作更难了', row: 0 },
      { text: '原来这叫做奥德赛', row: 0 },
      { text: '原来大家都有', row: 0 },
      { text: '阴暗潮湿的日子', row: 0 },
      { text: '这样啊', row: 0 },
      { text: '苦难', row: 1 },
      { text: '很痛苦很迷茫', row: 1 },
      { text: '焦虑源于方向感，焦虑源于自我认同', row: 1, featured: true, replies: 46 },
      { text: '大冒险时期', row: 1 },
      { text: '特别痛苦的时期', row: 1 },
      { text: '嘿嘿马里奥', row: 1 },
      { text: '28岁未成年', row: 1 },
      { text: '10后就不会了', row: 1 },
      { text: '我真的好讨厌这个阶段', row: 1 },
      { text: 'MyOdyssey', row: 1 },
      { text: '是的', row: 1 },
      { text: '虽然不能同时拥有一切', row: 1 },
      { text: '刚刚辞职回家', row: 1 },
      { text: '太对了', row: 1 },
      { text: '不管怎么选择都在失去另外一种人生', row: 2},
      { text: '很迷茫', row: 2 },
      { text: '我正处于这个阶段', row: 2 },
      { text: '晚期了', row: 2 },
      { text: '+1', row: 2 },
      { text: '毕业找工作中', row: 2 },
      { text: '困难时期', row: 2 },
      { text: '是啊我好焦虑', row: 2 },
      { text: '加速被社会驯化', row: 2 },
      { text: '真的诶', row: 2 },
    ],
  },

    {
    slide: 5,
    label: '功能4 | 聚合相同弹幕',
    info: {
      tag: '功能 4',
      title: '聚合相同弹幕，\n用数据传递情绪共振',
      description: '在开放式偏好表达的内容场景下，\n通过对相同弹幕聚合计数，让用户清晰感知同频观点的热度。',
    },
    annotations: [
      { text: '试玩从夯到拉，比如发送"拉完了"', side: 'left', yInPhone: 651 },
    ],
    video: 'https://g7wxjm6ewnwsi0wp.public.blob.vercel-storage.com/videos/usecase4.mov',
    avatar: 'usecase4.png',
    username: '@尖端锐评玩家',
    description: '从夯到拉 锐评一下奶茶店#从夯到拉排名#内容过于真实#夯爆了',
    captionOffset: 0,
    videoScale: 0.8,
    videoOffsetY: -8,
    disclaimerMaskHeight: 200,
    danmakus: [
      { text: '夯', row: 0 },
      { text: '夯', row: 0 },
      { text: '拉完了', row: 0 },
      { text: '顶级', row: 0 },
      { text: '拉完了', row: 0 },
      { text: 'NPC', row: 0 },
      { text: '顶级', row: 0 },
      { text: '拉完了', row: 0 },
      { text: 'NPC', row: 0 },
      { text: '拉完了', row: 1 },
      { text: '拉完了', row: 1 },
      { text: '拉完了', row: 1 },
      { text: 'NPC', row: 1 },
      { text: '夯爆了', row: 1 },
      { text: '拉完了', row: 1 },
      { text: 'NPC', row: 1 },
      { text: '拉完了', row: 1 },
      { text: '拉完了', row: 1 },
      { text: '拉完了', row: 1 },
      { text: '拉完了', row: 1 },
      { text: '夯爆了', row: 1 },
      { text: 'NPC', row: 1 },
      { text: '夯拉了', row: 1 },
      { text: '拉完了', row: 2},
      { text: '顶级', row: 2 },
      { text: '拉完了', row: 2 },
      { text: '拉完了', row: 2 },
      { text: '夯', row: 2 },
      { text: 'NPC', row: 2 },
      { text: '人上人', row: 2 },
      { text: '拉完了', row: 2 },
      { text: '拉完了', row: 2 },
      { text: '顶级', row: 2 },
    ],
  },


    {
    slide: 6,
    label: '功能5 |表情外延弹幕',
    info: {
      tag: '功能 5',
      title: '表情外延文字，\n放大集群式情绪',
      description: '引入更直观、更具冲击力的表情元素，通过满屏飘起的视觉效果递进情绪，放大用户的认同、期望、肯定等主观感受。',
    },
    annotations: [
      { text: '试着发送"接接接"', side: 'left', yInPhone: 675 },
    ],
    disableCounter: true,
    emojiFloat: true,
    video: 'https://g7wxjm6ewnwsi0wp.public.blob.vercel-storage.com/videos/usecase5-1.mov',
    avatar: 'usecase5-1.jpg',
    username: '@小笼包（见过两次版）',
    description: '所有人Lets接接接#演唱会抢票',
    captionOffset: 24,
    videoScale: 0.7,
    videoOffsetY: -12,
    syncRows: true,
    danmakus: [
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 0 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 1 },
      { text: '接接接', row: 2},
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
      { text: '接接接', row: 2 },
    ],
  },

    {
    slide: 7,
    label: '功能6 | 热点弹幕玩法',
    info: {
      tag: '功能 6',
      title: '衔接当下热点，\n为弹幕发送注入丰富内涵',
      description: '在节日、热点等强情绪节点，视频内容深度与表达意愿升级。\n对发送形态做差异化设计，提升弹幕发声的有用性。',
    },
    kiteDanmaku: true,
    disableCounter: true,
    willowLeaf: true,
    annotations: [
      { text: '试试发一条弹幕', side: 'left', yInPhone: 651 },
    ],
    video: 'https://g7wxjm6ewnwsi0wp.public.blob.vercel-storage.com/videos/usecase6.mov',
    avatar: 'usecase6.jpg',
    username: '@子扬ZYang',
    description: '又是清明雨上，不觉绿满江南 地点：杭州·茅家埠 2026.4.3',
    captionOffset: 0,
    danmakus: [
      { text: '清明雨上', row: 0 },
      { text: '清明时节雨纷纷', row: 0 },
      { text: '绿色生命力', row: 0 },
      { text: '清明安康', row: 0 },
      { text: '岁岁思故人', row: 0 },
      { text: '清明节安康', row: 0 },
      { text: '出门踏青', row: 0 },
      { text: '人间四月', row: 0 },
      { text: '清明雨上', row: 0 },
      { text: '想起了许嵩的歌', row: 1 },
      { text: '四月芳菲', row: 1 },
      { text: '又是一年清明时节', row: 1 },
      { text: '遥寄相思', row: 1 },
      { text: '愿故人无恙', row: 1 },
      { text: '有些伤感', row: 1 },
      { text: '打扫院子', row: 1 },
      { text: '黛草如烟', row: 1 },
      { text: '杨柳泛青', row: 1 },
      { text: '珍惜眼前人啊', row: 1 },
      { text: '珍惜当下', row: 1 },
      { text: '风景真好', row: 1 },
      { text: '空气很清新', row: 1 },
      { text: '又是清明', row: 1 },
      { text: '思念如连绵的雨', row: 2},
      { text: '春天来了', row: 2 },
      { text: '清明时节雨纷纷', row: 2 },
      { text: '清明下雨', row: 2 },
      { text: '小溪潺潺', row: 2 },
      { text: '思念堆积如山', row: 2 },
      { text: '万物生', row: 2 },
      { text: '好美', row: 2 },
      { text: '烟雨江南', row: 2 },
      { text: '杭州好美啊', row: 2 },
    ],
  },


  // ── 在此继续添加新的 demo ──────────────────────────────────
  // {
  //   slide: 8,          // 页面9
  //   label: '页面 9 · 用例 Demo',
  //   video: 'usecase3.mov',
  //   avatar: 'avatar-p9.jpg',
  //   username: '@用户名',
  //   description: '描述文字 #标签',
  //   captionOffset: 0,
  //   danmakus: [
  //     { text: '弹幕内容', row: 0 },
  //   ],
  // },
];

// 自动从 danmakus 按 row 分组，生成各页背景文案池
// 只排除标记了 plusOne:true 的条目，文本相同但未标记的背景弹幕仍可进入池
DEMOS.forEach(demo => {
  if (demo.danmakus && demo.danmakus.length > 0) {
    const pool = [[], [], []];
    demo.danmakus.forEach(d => {
      if (!d.plusOne) pool[d.row ?? 0].push(d.text);
    });
    // 去重，空行 fallback 用其他行
    demo.bgTexts = pool.map((arr, i) => {
      const unique = [...new Set(arr)];
      return unique.length > 0 ? unique : [...new Set(pool.flat())];
    });
  }
});

export default DEMOS;
